// Code generated by ent, DO NOT EDIT.

package ent

import (
	"tgent/ent/post"
	"tgent/ent/schema"
	"tgent/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	postFields := schema.Post{}.Fields()
	_ = postFields
	// postDescTitle is the schema descriptor for Title field.
	postDescTitle := postFields[0].Descriptor()
	// post.TitleValidator is a validator for the "Title" field. It is called by the builders before save.
	post.TitleValidator = postDescTitle.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescTgID is the schema descriptor for TgID field.
	userDescTgID := userFields[0].Descriptor()
	// user.TgIDValidator is a validator for the "TgID" field. It is called by the builders before save.
	user.TgIDValidator = userDescTgID.Validators[0].(func(string) error)
	// userDescName is the schema descriptor for Name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "Name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
}
